var searchData=
[
  ['ocrresulthandletype_25112',['OcrResultHandleType',['../struct_ocr_result_handle_type.html',1,'']]],
  ['offlinehtmlpagereturnvalue_25113',['OfflineHtmlPageReturnValue',['../classnn_1_1web_1_1_offline_html_page_return_value.html',1,'nn::web']]],
  ['openarg_25114',['OpenArg',['../structnn_1_1atk_1_1_fs_sound_archive_1_1_open_arg.html',1,'nn::atk::FsSoundArchive::OpenArg'],['../structnn_1_1spy_1_1_spy_controller_1_1_open_arg.html',1,'nn::spy::SpyController::OpenArg']]],
  ['option_25115',['Option',['../structnn_1_1atk_1_1viewer_1_1_sound_edit_1_1_option.html',1,'nn::atk::viewer::SoundEdit']]],
  ['opusbasicinfo_25116',['OpusBasicInfo',['../structnn_1_1codec_1_1_opus_basic_info.html',1,'nn::codec']]],
  ['opusdecoder_25117',['OpusDecoder',['../classnn_1_1codec_1_1_opus_decoder.html',1,'nn::codec']]],
  ['opusdecodertype_25118',['OpusDecoderType',['../structnn_1_1codec_1_1_opus_decoder_type.html',1,'nn::codec']]],
  ['opusencoder_25119',['OpusEncoder',['../classnn_1_1codec_1_1_opus_encoder.html',1,'nn::codec']]],
  ['opusencodertype_25120',['OpusEncoderType',['../structnn_1_1codec_1_1_opus_encoder_type.html',1,'nn::codec']]],
  ['opusinfoheader_25121',['OpusInfoHeader',['../structnn_1_1codec_1_1_opus_info_header.html',1,'nn::codec']]],
  ['opusmultistreamdecoder_25122',['OpusMultiStreamDecoder',['../classnn_1_1codec_1_1_opus_multi_stream_decoder.html',1,'nn::codec']]],
  ['opusmultistreamdecodertype_25123',['OpusMultiStreamDecoderType',['../structnn_1_1codec_1_1_opus_multi_stream_decoder_type.html',1,'nn::codec']]],
  ['opusmultistreaminfo_25124',['OpusMultiStreamInfo',['../structnn_1_1codec_1_1_opus_multi_stream_info.html',1,'nn::codec']]],
  ['otfkerningtable_25125',['OtfKerningTable',['../structnn_1_1fontll_1_1_otf_kerning_table.html',1,'nn::fontll']]],
  ['oui_25126',['Oui',['../structnn_1_1net_1_1_oui.html',1,'nn::net']]],
  ['outofmemoryeventarg_25127',['OutOfMemoryEventArg',['../structnn_1_1gfx_1_1_out_of_memory_event_arg.html',1,'nn::gfx']]],
  ['outputambientparam_25128',['OutputAmbientParam',['../classnn_1_1atk_1_1_output_ambient_param.html',1,'nn::atk']]],
  ['outputreceiver_25129',['OutputReceiver',['../classnn_1_1atk_1_1_output_receiver.html',1,'nn::atk']]]
];
