var searchData=
[
  ['sample_20descriptions_48238',['Sample Descriptions',['../_page_sample.html',1,'']]],
  ['sample_20for_20encoding_20jpegs_20and_20setting_20exif_20information_48239',['Sample for Encoding JPEGs and Setting Exif Information',['../_page_sample_image_jpeg_encoding.html',1,'PageSampleImage']]],
  ['sample_20for_20playing_20sounds_20using_20an_20additional_20sound_20archive_48240',['Sample for Playing Sounds Using an Additional Sound Archive',['../_page_sample_atk_addon_sound_archive.html',1,'PageSampleAtk']]],
  ['sample_20nfp_20library_20_28version_20supporting_20simultaneously_20accessing_20multiple_20nfc_20devices_29_48241',['Sample NFP Library (Version Supporting Simultaneously Accessing Multiple NFC Devices)',['../_page_sample_nfp_multi.html',1,'PageSampleNfp']]],
  ['sample_20that_20checks_20for_20purchase_20reports_48242',['Sample That Checks For Purchase Reports',['../_page_sample_ec_purchased_event.html',1,'PageSampleEc']]],
  ['sample_20that_20gets_20launch_20parameters_2e_48243',['Sample that gets launch parameters.',['../_page_sample_oe_launch_parameter.html',1,'PageSampleOe']]],
  ['save_20data_20functionality_20for_20debugging_20sample_48244',['Save Data Functionality for Debugging Sample',['../_page_sample_fs_save_data_for_debug.html',1,'PageSampleFs']]],
  ['saving_20an_20application_20screenshot_20and_20posting_20it_20to_20an_20sns_48245',['Saving an Application Screenshot and Posting It to an SNS',['../_page_sample_album_save_screenshot.html',1,'PageSampleAlbum']]],
  ['scalable_20font_20engine_20library_20samples_48246',['Scalable Font Engine Library Samples',['../_page_sample_fontll.html',1,'PageSample']]],
  ['sd_20card_20file_20system_20operations_20for_20debugging_2e_48247',['SD card file system operations for debugging.',['../_page_sample_fs_sd_card_for_debug.html',1,'PageSampleFs']]],
  ['selecting_20performance_20configurations_20sample_48248',['Selecting Performance Configurations Sample',['../_page_sample_oe_performance.html',1,'PageSampleOe']]],
  ['semaphore_20sample_48249',['Semaphore Sample',['../_page_sample_os_semaphore.html',1,'PageSampleOs']]],
  ['settings_48250',['Settings',['../_page_sample_settings.html',1,'PageSample']]],
  ['simple_20audio_20playback_20sample_48251',['Simple Audio Playback Sample',['../_page_sample_atk_simple.html',1,'PageSampleAtk']]],
  ['simple_20controls_20for_20the_20ir_20motion_20camera_20clustering_20mode_20sample_48252',['Simple controls for the IR Motion Camera Clustering Mode Sample',['../_page_sample_ir_sensor_clustering_basic.html',1,'PageSampleIrSensor']]],
  ['simple_20controls_20for_20the_20ir_20motion_20camera_20infrared_20led_20mode_48253',['Simple Controls for the IR Motion Camera Infrared LED Mode',['../_page_sample_ir_sensor_ir_led_basic.html',1,'PageSampleIrSensor']]],
  ['simple_20controls_20for_20the_20ir_20motion_20camera_20moment_20mode_20sample_48254',['Simple Controls for the IR Motion Camera Moment Mode Sample',['../_page_sample_ir_sensor_moment_basic.html',1,'PageSampleIrSensor']]],
  ['simple_20debugfont_20sample_48255',['Simple DebugFont Sample',['../_page_sample_debug_font_simple.html',1,'PageSampleGfxUtil']]],
  ['simple_20effect_20display_20sample_48256',['Simple Effect Display Sample',['../_page_sample_vfx_simple.html',1,'PageSampleVfx']]],
  ['simple_20g3ddemo_20sample_48257',['Simple G3dDemo Sample',['../_page_sample_g3d_simple.html',1,'PageSampleG3d']]],
  ['simple_20gpu_20calculations_20sample_48258',['Simple GPU Calculations Sample',['../_page_sample_gfx_simple_compute.html',1,'PageSampleGfx']]],
  ['simple_20graphics_20sample_48259',['Simple Graphics Sample',['../_page_sample_gfx_simple.html',1,'PageSampleGfx']]],
  ['simple_20https_20communication_20with_20ssl_20library_48260',['Simple Https communication with SSL library',['../_page_sample_ssl_simple.html',1,'PageSampleSsl']]],
  ['simple_20mii_20character_20rendering_20sample_48261',['Simple Mii Character Rendering Sample',['../_page_sample_mii_simple.html',1,'PageSampleMii']]],
  ['simple_20mii_20icon_20rendering_20sample_48262',['Simple Mii Icon Rendering Sample',['../_page_sample_mii_simple_icon.html',1,'PageSampleMii']]],
  ['simple_20networking_20with_20target_20manager_20sample_48263',['Simple Networking With Target Manager Sample',['../_page_sample_tm_simple_net.html',1,'PageSampleTm']]],
  ['simple_20target_20manager_20sample_48264',['Simple Target Manager Sample',['../_page_sample_tm_simple.html',1,'PageSampleTm']]],
  ['simple_20vibration_20motor_20controls_20sample_48265',['Simple Vibration Motor Controls Sample',['../_page_sample_hid_vibration_basic.html',1,'PageSampleHid']]],
  ['simultaneously_20using_20audio_20input_20and_20output_20features_20sample_48266',['Simultaneously Using Audio Input and Output Features Sample',['../_page_sample_audio_audio_echoback.html',1,'PageSampleAudio']]],
  ['socket_20communication_20with_20the_20socket_20api_20sample_48267',['Socket Communication With the Socket API Sample',['../_page_sample_socket_basic.html',1,'PageSampleSocket']]],
  ['socket_20library_20samples_48268',['Socket Library Samples',['../_page_sample_socket.html',1,'PageSample']]],
  ['socket_20statistics_20overlay_48269',['Socket Statistics Overlay',['../_page_sample_socket_statistics_overlay.html',1,'PageSampleSocket']]],
  ['socketeventfd_20sample_48270',['SocketEventFd sample',['../_page_sample_socket_event_fd.html',1,'PageSampleSocket']]],
  ['software_20keyboard_20library_20samples_48271',['Software Keyboard Library Samples',['../_page_sample_swkbd.html',1,'PageSample']]],
  ['sound3d_20playback_20sample_48272',['Sound3D Playback Sample',['../_page_sample_atk_sound3_d.html',1,'PageSampleAtk']]],
  ['spatial_20navigation_20in_20the_20web_20applet_20sample_48273',['Spatial Navigation in the Web Applet Sample',['../_page_sample_web_demo_spatial_navigation.html',1,'PageSampleWeb']]],
  ['splittertype_20sample_20program_48274',['SplitterType Sample Program',['../_page_sample_audio_audio_splitter.html',1,'PageSampleAudio']]],
  ['spyatk_48275',['SpyAtk',['../_page_sample_spy_atk.html',1,'PageSampleSpy']]],
  ['spyaudio_20sample_48276',['SpyAudio Sample',['../_page_sample_spy_audio.html',1,'PageSampleSpy']]],
  ['ssl_20library_20samples_48277',['SSL Library Samples',['../_page_sample_ssl.html',1,'PageSample']]],
  ['standardusersystemclock_20sample_48278',['StandardUserSystemClock Sample',['../_page_sample_time_standard_user_system_clock.html',1,'PageSampleTime']]],
  ['start_20up_20the_20software_20keyboard_20applet_20sample_48279',['Start Up the Software Keyboard Applet Sample',['../_page_sample_swkbd_simple.html',1,'PageSampleSwkbd']]],
  ['streaming_20decompression_20sample_48280',['Streaming Decompression Sample',['../_page_sample_util_streaming_decompression.html',1,'PageSampleUtil']]]
];
